# Generated by Django 4.0.6 on 2022-07-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='Fea',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
